{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6vkj3qavbndgritoepjse5pyme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.1.0.jar",
          "url": "soracom-inventory-agent-for-java-core-0.1.0.jar",
          "size": 127581,
          "sha512": "2c25d736da57a34bca2ccea741e30fdfc1baad712f47ce76d41cfd0ed5e11fb60dd978c119beb02bff5351fd4c0def6061cf8fd19e7c0a22ac4f32fa7b163577",
          "sha256": "cf75b088ce14eb430e716f3ffbf86e2742b943bb71b3d57511713f38702880d",
          "sha1": "934a375498409f13082206608623217b6eb0d398",
          "md5": "7b2632937652b632dc289495a65f8d86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.1.0.jar",
          "url": "soracom-inventory-agent-for-java-core-0.1.0.jar",
          "size": 127581,
          "sha512": "2c25d736da57a34bca2ccea741e30fdfc1baad712f47ce76d41cfd0ed5e11fb60dd978c119beb02bff5351fd4c0def6061cf8fd19e7c0a22ac4f32fa7b163577",
          "sha256": "cf75b088ce14eb430e716f3ffbf86e2742b943bb71b3d57511713f38702880d",
          "sha1": "934a375498409f13082206608623217b6eb0d398",
          "md5": "7b2632937652b632dc289495a65f8d86"
        }
      ]
    }
  ]
}
