{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "rnqk3vxyijhxbkpnjcoj43xmy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.7-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.7-20200107.121009-1.jar",
          "size": 11862,
          "sha512": "c1f33af9ab7e5bddfbf710ef8094206a2c749ff9f704511137d3f7985fb5a9c84e711049b366ef2e1c9d8ccbfffdc46a1048fb6c3315f38b8c2efd08b9cfc3d5",
          "sha256": "eb1861067679aee0f8af0851eaf402fed8a5182c9059fcd3c07544d03c308d66",
          "sha1": "26128dde21b5f9a8d9170f933500be948f7acc52",
          "md5": "79e24800170a07143ccadcb2d6c4bc03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.7-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.7-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.7-20200107.121009-1.jar",
          "size": 11862,
          "sha512": "c1f33af9ab7e5bddfbf710ef8094206a2c749ff9f704511137d3f7985fb5a9c84e711049b366ef2e1c9d8ccbfffdc46a1048fb6c3315f38b8c2efd08b9cfc3d5",
          "sha256": "eb1861067679aee0f8af0851eaf402fed8a5182c9059fcd3c07544d03c308d66",
          "sha1": "26128dde21b5f9a8d9170f933500be948f7acc52",
          "md5": "79e24800170a07143ccadcb2d6c4bc03"
        }
      ]
    }
  ]
}
