{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6vkj3qavbndgritoepjse5pyme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.1.0.jar",
          "url": "soracom-inventory-agent-for-java-example-0.1.0.jar",
          "size": 12003,
          "sha512": "74492b73bbaff44c2b4c839c19c23f5e78ba536e9fcdd5e51da9289703d41f9048c5c5918575228319a985318fad2d0a12b1513c7cfa545fa5e6239512e3f9a4",
          "sha256": "b82f840e3e1a9752b14ea7677b109059f12e713925c0ccace1553ef8d3d3774f",
          "sha1": "c632f4e6fe9676b51ee38f739713a9b7b22a02ea",
          "md5": "d8b307c6b0660e46115921d3d4e13710"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.1.0.jar",
          "url": "soracom-inventory-agent-for-java-example-0.1.0.jar",
          "size": 12003,
          "sha512": "74492b73bbaff44c2b4c839c19c23f5e78ba536e9fcdd5e51da9289703d41f9048c5c5918575228319a985318fad2d0a12b1513c7cfa545fa5e6239512e3f9a4",
          "sha256": "b82f840e3e1a9752b14ea7677b109059f12e713925c0ccace1553ef8d3d3774f",
          "sha1": "c632f4e6fe9676b51ee38f739713a9b7b22a02ea",
          "md5": "d8b307c6b0660e46115921d3d4e13710"
        }
      ]
    }
  ]
}
