{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ji2gbsqpizgxhpzvouublrc5sm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "48b750b610e9da2c2d4322ccd73caa4d9643614e49fbc1f8bb2dc25b320024c9f55c29a84002ebed290177b0804e09b12895fb69edea7e0d85363354559e6b56",
          "sha256": "5c2f50ccb79f28ff5324d9203232992773151d6456a254800a53408a09dfef0c",
          "sha1": "cecf60bd6e6adf5c63cde7c77d5090b021024ad5",
          "md5": "1b79c397343d8950a2ad957cfa313fdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "48b750b610e9da2c2d4322ccd73caa4d9643614e49fbc1f8bb2dc25b320024c9f55c29a84002ebed290177b0804e09b12895fb69edea7e0d85363354559e6b56",
          "sha256": "5c2f50ccb79f28ff5324d9203232992773151d6456a254800a53408a09dfef0c",
          "sha1": "cecf60bd6e6adf5c63cde7c77d5090b021024ad5",
          "md5": "1b79c397343d8950a2ad957cfa313fdc"
        }
      ]
    }
  ]
}
