{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zgzcdyvucvaafoasp3garrvfaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "5b7fcd33941bc17d4b27c1154c9a794021488c1ec06e29648b6de426a1369847c992f055f75b378006e210b0bcb3ca09e2c56772662c4022e0f64a7ece03a0fa",
          "sha256": "91a0aa4d6ffba1832d92f7ba6a82dadbb416ae2665a520dc26bd6146c22c9205",
          "sha1": "b7fa1dd45b36338ebd3ca3cad10c4e0e04caf8d5",
          "md5": "54bf1fec71313b517f079db94cb1f81c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "5b7fcd33941bc17d4b27c1154c9a794021488c1ec06e29648b6de426a1369847c992f055f75b378006e210b0bcb3ca09e2c56772662c4022e0f64a7ece03a0fa",
          "sha256": "91a0aa4d6ffba1832d92f7ba6a82dadbb416ae2665a520dc26bd6146c22c9205",
          "sha1": "b7fa1dd45b36338ebd3ca3cad10c4e0e04caf8d5",
          "md5": "54bf1fec71313b517f079db94cb1f81c"
        }
      ]
    }
  ]
}
