{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ckgmfaa4zfeo5ewoqomjquktea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "e240df2bd0ec0843f83d966f98eff6d42379687809a47c2159f0cb420e20f1dfc08f180252aaa5b5d5ad5489a946a584775da9665c2197bce497d0a7693857e6",
          "sha256": "bf5b41455bedb9846b75f02fdceb22d5c5591d4a5c48545a6749df02fc7830f",
          "sha1": "8fe1eedd66e880c7aabf3e57ba031203dac9fca2",
          "md5": "271c2646e42b4197bd6c6c2f4afedb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.9.jar",
          "size": 12003,
          "sha512": "e240df2bd0ec0843f83d966f98eff6d42379687809a47c2159f0cb420e20f1dfc08f180252aaa5b5d5ad5489a946a584775da9665c2197bce497d0a7693857e6",
          "sha256": "bf5b41455bedb9846b75f02fdceb22d5c5591d4a5c48545a6749df02fc7830f",
          "sha1": "8fe1eedd66e880c7aabf3e57ba031203dac9fca2",
          "md5": "271c2646e42b4197bd6c6c2f4afedb5"
        }
      ]
    }
  ]
}
