{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "2lttpx6pgndc5gyfgz2mtdnlse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201014.074716-1.jar",
          "size": 111099,
          "sha512": "5bff375abc2bcd38b89fb8414991d032a191998f583f8dc568b3e9e122ef1210471be761d0070eaa214d2ae8e630c26f265e0144cc2d81347e099a2f09e9b613",
          "sha256": "e06f0175643bb7fcefaf6fc0438adcad45222a5f6a799cd528e8dc236d497b03",
          "sha1": "16e146ce6bc81dfb2921dee65f7c19ad0ee9fab8",
          "md5": "31c7a50b63c0a6afd13889b53720917a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201014.074716-1.jar",
          "size": 111099,
          "sha512": "5bff375abc2bcd38b89fb8414991d032a191998f583f8dc568b3e9e122ef1210471be761d0070eaa214d2ae8e630c26f265e0144cc2d81347e099a2f09e9b613",
          "sha256": "e06f0175643bb7fcefaf6fc0438adcad45222a5f6a799cd528e8dc236d497b03",
          "sha1": "16e146ce6bc81dfb2921dee65f7c19ad0ee9fab8",
          "md5": "31c7a50b63c0a6afd13889b53720917a"
        }
      ]
    }
  ]
}
