{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "bj5tgotwondmbcr3p3og6tdo6a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201016.062349-1.jar",
          "size": 110636,
          "sha512": "ced57a3b187abd59c2faf810f42b29181485b333476e7ecdda51362fecd94dfaa2cbec95555ce06e9cb54d5e0c71b973b134e0317eb9cac04af99fc9e3dc4cea",
          "sha256": "ee561973b13a00c08ffcb16c1010bc70950f2b70dd8176cbbc13812611b20c7a",
          "sha1": "593f9f28597039e0c5f914d19610237e8df18393",
          "md5": "8e49ac76063e8475e2adfd7132dc3aca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201016.062349-1.jar",
          "size": 110636,
          "sha512": "ced57a3b187abd59c2faf810f42b29181485b333476e7ecdda51362fecd94dfaa2cbec95555ce06e9cb54d5e0c71b973b134e0317eb9cac04af99fc9e3dc4cea",
          "sha256": "ee561973b13a00c08ffcb16c1010bc70950f2b70dd8176cbbc13812611b20c7a",
          "sha1": "593f9f28597039e0c5f914d19610237e8df18393",
          "md5": "8e49ac76063e8475e2adfd7132dc3aca"
        }
      ]
    }
  ]
}
