{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "o26ooqrnkvaldcn7icovkceela"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201016.063844-1.jar",
          "size": 110636,
          "sha512": "f9801fde6132c30d6b54c00dc5cfacd2a6569a14ea8389328b6c1790921f87eabeee78174876f2e18a5f05268b0bf27f6483466b89c4e2cf7bf1fbd6e1a4c6ce",
          "sha256": "188b665882e6f2b8c79435680110ba085b54552424e122c82ae3a850549a778f",
          "sha1": "49d724975c7e7fe80c8d7b16222e78ccab97a46",
          "md5": "24508af844f8e4fb4d86de699732e4f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.0.0-M6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.8-20201016.063844-1.jar",
          "size": 110636,
          "sha512": "f9801fde6132c30d6b54c00dc5cfacd2a6569a14ea8389328b6c1790921f87eabeee78174876f2e18a5f05268b0bf27f6483466b89c4e2cf7bf1fbd6e1a4c6ce",
          "sha256": "188b665882e6f2b8c79435680110ba085b54552424e122c82ae3a850549a778f",
          "sha1": "49d724975c7e7fe80c8d7b16222e78ccab97a46",
          "md5": "24508af844f8e4fb4d86de699732e4f0"
        }
      ]
    }
  ]
}
