{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "hiv6pk5ernfrxg6irztxbtvmou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.10-20210407.122610-1.jar",
          "size": 127581,
          "sha512": "277e32440bd32dc63d4bf2287eaa0769e8b14db9651804be8075773ec342aa8562cd6d6d12164e851b2ae1c0f658b6ca42177e69e1dfdf266d015c4abdb83a5d",
          "sha256": "e8aaf1473f311c7a880f5be7520babde021706ccec49c6b06736c4817613b3b",
          "sha1": "c7933a63f6444db2a6921b2269eb6838537771f8",
          "md5": "58144324f2d89a4bde21d864e22faa8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.10-20210407.122610-1.jar",
          "size": 127581,
          "sha512": "277e32440bd32dc63d4bf2287eaa0769e8b14db9651804be8075773ec342aa8562cd6d6d12164e851b2ae1c0f658b6ca42177e69e1dfdf266d015c4abdb83a5d",
          "sha256": "e8aaf1473f311c7a880f5be7520babde021706ccec49c6b06736c4817613b3b",
          "sha1": "c7933a63f6444db2a6921b2269eb6838537771f8",
          "md5": "58144324f2d89a4bde21d864e22faa8f"
        }
      ]
    }
  ]
}
