{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ansx3qvuejd5zaymo54u5ibguy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.10-20210407.122844-1.jar",
          "size": 127581,
          "sha512": "f8768c16c0b1fcb436c570567967f10cb320d0c8c8d78d516f155fbe5030f1bd04eb45997b25955053e10607cf32a6f7744ac121c37dba187f52e10ae7fc6c00",
          "sha256": "5ce54b0a91e76700da7796e3a4f9062229136153122064a51922e6934fbc400e",
          "sha1": "42f24f98115f2b961cb3b559bfb0984ccd0e7ca3",
          "md5": "bf9fda65c6279c3b3e5bd673924999a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.10-20210407.122844-1.jar",
          "size": 127581,
          "sha512": "f8768c16c0b1fcb436c570567967f10cb320d0c8c8d78d516f155fbe5030f1bd04eb45997b25955053e10607cf32a6f7744ac121c37dba187f52e10ae7fc6c00",
          "sha256": "5ce54b0a91e76700da7796e3a4f9062229136153122064a51922e6934fbc400e",
          "sha1": "42f24f98115f2b961cb3b559bfb0984ccd0e7ca3",
          "md5": "bf9fda65c6279c3b3e5bd673924999a6"
        }
      ]
    }
  ]
}
