{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mbc34f7pe5f6dg747q2725ox3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8.jar",
          "size": 12003,
          "sha512": "e534a324a871b9717119515e0d6e9092075442aebce927b42e36ce215afea5be9981308b77ee5488d36b572ea200a256f4e049ab96c8872ecd6ca0360e2b32b4",
          "sha256": "90c8e4d7d9a20f162b6124c04ae950ed24869c157c2dafcdb066448e3b651bbb",
          "sha1": "57d7e0ff01e1c19109168bf8e461e17f821eb52",
          "md5": "b81ab54bd19bb32ef2b41e6197048340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8.jar",
          "size": 12003,
          "sha512": "e534a324a871b9717119515e0d6e9092075442aebce927b42e36ce215afea5be9981308b77ee5488d36b572ea200a256f4e049ab96c8872ecd6ca0360e2b32b4",
          "sha256": "90c8e4d7d9a20f162b6124c04ae950ed24869c157c2dafcdb066448e3b651bbb",
          "sha1": "57d7e0ff01e1c19109168bf8e461e17f821eb52",
          "md5": "b81ab54bd19bb32ef2b41e6197048340"
        }
      ]
    }
  ]
}
