{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "hwhy65disvguxdzjvtnvfcu7au"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.1.1.jar",
          "url": "soracom-inventory-agent-for-java-example-0.1.1.jar",
          "size": 12003,
          "sha512": "212cee1bd16615128bf74b0c861af4dbc8a4c747f2e09b4a1024b4f0446ef56c196d86b97b1a607e71e0c414537270513bc4dd0beb86e8570eda1f66c11e918d",
          "sha256": "8209eeb541a6c9c5c1f0f419bc3d638394b1664eb163ba72f5000b546e1b9980",
          "sha1": "a012de3e349c95558bdb4a593296e6ac63cab1ca",
          "md5": "ea1c227eadfa6a395220b674edfac015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.1.1.jar",
          "url": "soracom-inventory-agent-for-java-example-0.1.1.jar",
          "size": 12003,
          "sha512": "212cee1bd16615128bf74b0c861af4dbc8a4c747f2e09b4a1024b4f0446ef56c196d86b97b1a607e71e0c414537270513bc4dd0beb86e8570eda1f66c11e918d",
          "sha256": "8209eeb541a6c9c5c1f0f419bc3d638394b1664eb163ba72f5000b546e1b9980",
          "sha1": "a012de3e349c95558bdb4a593296e6ac63cab1ca",
          "md5": "ea1c227eadfa6a395220b674edfac015"
        }
      ]
    }
  ]
}
