{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "o26ooqrnkvaldcn7icovkceela"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.063844-1.jar",
          "size": 11833,
          "sha512": "1e3ef7f13ab972fc5c2d1d45f73d0aef335701bbc7c327a1d7171dfba7ee9a15c3c96f78abc2717004c0f3f3e86eb03db487325a169d96f9aa1b7fb5c1989584",
          "sha256": "6189052603b095b06351f72ef500d7ba8e8cc59753bee38df1880288387005ae",
          "sha1": "aee3b54251aea806dc77383ee232a7957fb81313",
          "md5": "79befdec66d52ccbd90d6d0f5a9b2a18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.063844-1.jar",
          "size": 11833,
          "sha512": "1e3ef7f13ab972fc5c2d1d45f73d0aef335701bbc7c327a1d7171dfba7ee9a15c3c96f78abc2717004c0f3f3e86eb03db487325a169d96f9aa1b7fb5c1989584",
          "sha256": "6189052603b095b06351f72ef500d7ba8e8cc59753bee38df1880288387005ae",
          "sha1": "aee3b54251aea806dc77383ee232a7957fb81313",
          "md5": "79befdec66d52ccbd90d6d0f5a9b2a18"
        }
      ]
    }
  ]
}
