{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "2trietqwsncrxp7advyfhvdomy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.061851-1.jar",
          "size": 11833,
          "sha512": "ef18773e7c7cbcfae273df2e1852afcb6c8a6781915a052bdfb75a29074ff7eb152430ae1ac65ddceaa3169c234f9ef60d3b83de7eeb3ad2268a79cc2db3b3d2",
          "sha256": "3207778c02c4588a6bc2c01ef06225bbb3a3ca11088d0adad98050b39bb833b6",
          "sha1": "2fd8f1d11ddf73a72879e4622cc47b9f7f1fad28",
          "md5": "ca4c64d564a2105ef09d8c6054cc6072"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.061851-1.jar",
          "size": 11833,
          "sha512": "ef18773e7c7cbcfae273df2e1852afcb6c8a6781915a052bdfb75a29074ff7eb152430ae1ac65ddceaa3169c234f9ef60d3b83de7eeb3ad2268a79cc2db3b3d2",
          "sha256": "3207778c02c4588a6bc2c01ef06225bbb3a3ca11088d0adad98050b39bb833b6",
          "sha1": "2fd8f1d11ddf73a72879e4622cc47b9f7f1fad28",
          "md5": "ca4c64d564a2105ef09d8c6054cc6072"
        }
      ]
    }
  ]
}
