{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mqzjuurt4jalxcbp45ho7vzo4y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.064706-1.jar",
          "size": 11833,
          "sha512": "38bdb12c4f9ce618f51e7de017b4a733ad7e4635e345f303b9d4c8141aae8da72758c6251283bd8276c7ceb8aa4938416a7e1a3061b6762fbe6c5fa85857e5bd",
          "sha256": "9a7669d64b6562e681de265cfc2fdc249819841689edf2f1f2d27a5f610be290",
          "sha1": "5fa83a2412f2c940f3c4bb1164dcdacc1d200447",
          "md5": "c71ca8660519c46295a731ad3bcdc579"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.064706-1.jar",
          "size": 11833,
          "sha512": "38bdb12c4f9ce618f51e7de017b4a733ad7e4635e345f303b9d4c8141aae8da72758c6251283bd8276c7ceb8aa4938416a7e1a3061b6762fbe6c5fa85857e5bd",
          "sha256": "9a7669d64b6562e681de265cfc2fdc249819841689edf2f1f2d27a5f610be290",
          "sha1": "5fa83a2412f2c940f3c4bb1164dcdacc1d200447",
          "md5": "c71ca8660519c46295a731ad3bcdc579"
        }
      ]
    }
  ]
}
