{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "g6mvvk33ivhv5i5qabusaus4he"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201014.071814-1.jar",
          "size": 11862,
          "sha512": "1eeec9d7751b8226609ea3c1825fcf54ca81ab5c65fae339c43dfd9f8dcba541234d593001ae6f132c7e4f8d48aba36441b9dbc4a6f62ae51fbc172cb4beae14",
          "sha256": "b57d0cf24956aef2b1f4a8da961876ce10f7a3b996269ebede45f626240fe07d",
          "sha1": "74af9786df156bc6e81c47ef31b5e18c027ce84a",
          "md5": "4521acb2abb0d106ff839f1e91ec0b4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201014.071814-1.jar",
          "size": 11862,
          "sha512": "1eeec9d7751b8226609ea3c1825fcf54ca81ab5c65fae339c43dfd9f8dcba541234d593001ae6f132c7e4f8d48aba36441b9dbc4a6f62ae51fbc172cb4beae14",
          "sha256": "b57d0cf24956aef2b1f4a8da961876ce10f7a3b996269ebede45f626240fe07d",
          "sha1": "74af9786df156bc6e81c47ef31b5e18c027ce84a",
          "md5": "4521acb2abb0d106ff839f1e91ec0b4f"
        }
      ]
    }
  ]
}
