{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "hxlyvtrcw5fnzat2ctnqlewo7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.054639-1.jar",
          "size": 11833,
          "sha512": "b76531a08ecb49532ddeef76e5652150063bfa494db1adfcb0377a60569931bf1f0f4ff06057733d1efb11261fb464c996d5565727e1b0e07ee235b57f2c6d66",
          "sha256": "d77f807f38c5cca10253652fa75900fb9554669f4dee3bace5c4f8afe821e733",
          "sha1": "baa23c607a49c71202917cd8d869d927558d19e2",
          "md5": "4d0683541481943324dc9fd5337433dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.054639-1.jar",
          "size": 11833,
          "sha512": "b76531a08ecb49532ddeef76e5652150063bfa494db1adfcb0377a60569931bf1f0f4ff06057733d1efb11261fb464c996d5565727e1b0e07ee235b57f2c6d66",
          "sha256": "d77f807f38c5cca10253652fa75900fb9554669f4dee3bace5c4f8afe821e733",
          "sha1": "baa23c607a49c71202917cd8d869d927558d19e2",
          "md5": "4d0683541481943324dc9fd5337433dd"
        }
      ]
    }
  ]
}
