{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "fwbxmxwvljgwnottruyh63rxam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074138-1.jar",
          "size": 11833,
          "sha512": "bec7ae6b6a2097250554fee6031a9376e204b15358e2b14bc92f3059ef0118caaa6343bbdf2123707592b3b43f895b9f2937691cc515dadefc12498e22336ee3",
          "sha256": "f3764c2eaea0333f25a8c5ced5a980ff9c700a3a40e95f3a9f1752f20df16fd5",
          "sha1": "11af90033e2b400e9cf8a31c167c060f624f4790",
          "md5": "14ab528b089c663d4a4122c761778f45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074138-1.jar",
          "size": 11833,
          "sha512": "bec7ae6b6a2097250554fee6031a9376e204b15358e2b14bc92f3059ef0118caaa6343bbdf2123707592b3b43f895b9f2937691cc515dadefc12498e22336ee3",
          "sha256": "f3764c2eaea0333f25a8c5ced5a980ff9c700a3a40e95f3a9f1752f20df16fd5",
          "sha1": "11af90033e2b400e9cf8a31c167c060f624f4790",
          "md5": "14ab528b089c663d4a4122c761778f45"
        }
      ]
    }
  ]
}
