{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "znvgwxqdanfebpua2fwjv5s644"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.060853-1.jar",
          "size": 11862,
          "sha512": "e1b7710ae20dc60a6c7fb94bed19b30e35c98deceec5603ecda0d2b73ee51ce357d9acd55d952120519b5349fec174fd5e127888bfdfb40d06af5222e518cce4",
          "sha256": "d9afc1287d84e8dd634bbc1350558bb1b64a2357eeb398111691a2694024f008",
          "sha1": "a0e47b943acb3ae6031364ee7f0be348bd6b9b08",
          "md5": "ee3d455ac0e48c70d15d3b6e47691dc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.060853-1.jar",
          "size": 11862,
          "sha512": "e1b7710ae20dc60a6c7fb94bed19b30e35c98deceec5603ecda0d2b73ee51ce357d9acd55d952120519b5349fec174fd5e127888bfdfb40d06af5222e518cce4",
          "sha256": "d9afc1287d84e8dd634bbc1350558bb1b64a2357eeb398111691a2694024f008",
          "sha1": "a0e47b943acb3ae6031364ee7f0be348bd6b9b08",
          "md5": "ee3d455ac0e48c70d15d3b6e47691dc8"
        }
      ]
    }
  ]
}
