{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "h47f2cs2ofehlmmohtsop7radi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.072400-1.jar",
          "size": 11833,
          "sha512": "e84b37b2888c4afac702cba4563b574b087b360f07b0c8ce9ececc4037359f9b7931f786d82685d5ed0c5ee4bc82436546bd468ff1f87d17021dbc7ae611b63c",
          "sha256": "18bada31ece419e74bd11dc881a23bff05e13eae08ba9c4f7fb108e5d19b4c3a",
          "sha1": "d3da2538ce0f7c65c23456deba8ea9c6e8364d52",
          "md5": "67ac559984febda6b9c9bc1e9dd8ab96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.072400-1.jar",
          "size": 11833,
          "sha512": "e84b37b2888c4afac702cba4563b574b087b360f07b0c8ce9ececc4037359f9b7931f786d82685d5ed0c5ee4bc82436546bd468ff1f87d17021dbc7ae611b63c",
          "sha256": "18bada31ece419e74bd11dc881a23bff05e13eae08ba9c4f7fb108e5d19b4c3a",
          "sha1": "d3da2538ce0f7c65c23456deba8ea9c6e8364d52",
          "md5": "67ac559984febda6b9c9bc1e9dd8ab96"
        }
      ]
    }
  ]
}
