{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "vv6g422bcfc5xlwkub3bh4ndzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.063756-1.jar",
          "size": 11833,
          "sha512": "6eeea1a3a88f69dcfefb7c6e9ef11e6c43ecbc7fff506e4de1daf9314620e5943e3f5d7a500ba13a5b3d48d7db4187c805875d1d236033fb916c05a0179e324e",
          "sha256": "55cb6a19d01dd46fb494f77d7dc69075e3b761fbf9443b5888d3c07abcc9196b",
          "sha1": "c816fdf40e3d75c2b6d7b05a002fff5e8192e95d",
          "md5": "8555fc4273210d5fc5780239798ff4a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.063756-1.jar",
          "size": 11833,
          "sha512": "6eeea1a3a88f69dcfefb7c6e9ef11e6c43ecbc7fff506e4de1daf9314620e5943e3f5d7a500ba13a5b3d48d7db4187c805875d1d236033fb916c05a0179e324e",
          "sha256": "55cb6a19d01dd46fb494f77d7dc69075e3b761fbf9443b5888d3c07abcc9196b",
          "sha1": "c816fdf40e3d75c2b6d7b05a002fff5e8192e95d",
          "md5": "8555fc4273210d5fc5780239798ff4a5"
        }
      ]
    }
  ]
}
