{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "bj5tgotwondmbcr3p3og6tdo6a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.062349-1.jar",
          "size": 11833,
          "sha512": "f7f03404124882c10e7cfa5263ad68308a9ae980a1cb94101b744a03738a0fb870a5d3833e5b9b151e7fea4e88a9cf3ea2b25d7c9fd7fc4a10895561a6696c26",
          "sha256": "21156a5e93049fe4937d71a8b7aaff951e3145b4028018b1c039d66f3745934b",
          "sha1": "39178879a3540074c7f3854510c875bb0756f3f8",
          "md5": "189dee537826baee57fd15126b7f7750"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.062349-1.jar",
          "size": 11833,
          "sha512": "f7f03404124882c10e7cfa5263ad68308a9ae980a1cb94101b744a03738a0fb870a5d3833e5b9b151e7fea4e88a9cf3ea2b25d7c9fd7fc4a10895561a6696c26",
          "sha256": "21156a5e93049fe4937d71a8b7aaff951e3145b4028018b1c039d66f3745934b",
          "sha1": "39178879a3540074c7f3854510c875bb0756f3f8",
          "md5": "189dee537826baee57fd15126b7f7750"
        }
      ]
    }
  ]
}
