{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nx2iv4c675ba7c4qbxcf5svily"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074103-1.jar",
          "size": 11833,
          "sha512": "3e5ea8d5b9af2fd5510561dd08e3eedd9b239fedece4c8ca2673c6cdddff40ce7f3c22b6c4fef3d64ba0d6c67372e7cdcecbc9d74bd76b07d6a704c1cc9e126a",
          "sha256": "68abcdee62cddc05e70d932cff5053af6e37ba36a700772fa13f30b18b92555c",
          "sha1": "ce128089d3069039e52fac9806fee6b7c583e765",
          "md5": "f8748fe60c8bd130841758c96ca5bf07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074103-1.jar",
          "size": 11833,
          "sha512": "3e5ea8d5b9af2fd5510561dd08e3eedd9b239fedece4c8ca2673c6cdddff40ce7f3c22b6c4fef3d64ba0d6c67372e7cdcecbc9d74bd76b07d6a704c1cc9e126a",
          "sha256": "68abcdee62cddc05e70d932cff5053af6e37ba36a700772fa13f30b18b92555c",
          "sha1": "ce128089d3069039e52fac9806fee6b7c583e765",
          "md5": "f8748fe60c8bd130841758c96ca5bf07"
        }
      ]
    }
  ]
}
