{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6qx3sxs5pjha7hwjkjyovms33y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.061959-1.jar",
          "size": 11833,
          "sha512": "b4c661b01b680374fdc882bbe57309a8ec2ecbcfe6c16fa9bf2f1981068ebcf1f8b55793a2abfce07d9990608463651a84726a7099f7137bfc591fef92717b32",
          "sha256": "ba35f2bdc6e792c528986334e48021513a5c6c362a9568c50a83a7102eb410e7",
          "sha1": "f10f31bc0e32cdb60ae64392d94a811bded71acb",
          "md5": "1113ce15c8a1a476a62e5f551a4af340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.061959-1.jar",
          "size": 11833,
          "sha512": "b4c661b01b680374fdc882bbe57309a8ec2ecbcfe6c16fa9bf2f1981068ebcf1f8b55793a2abfce07d9990608463651a84726a7099f7137bfc591fef92717b32",
          "sha256": "ba35f2bdc6e792c528986334e48021513a5c6c362a9568c50a83a7102eb410e7",
          "sha1": "f10f31bc0e32cdb60ae64392d94a811bded71acb",
          "md5": "1113ce15c8a1a476a62e5f551a4af340"
        }
      ]
    }
  ]
}
