{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "fdozzcecuzamvgpsq26jch6evq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074218-1.jar",
          "size": 11833,
          "sha512": "b06cfd98af52fec4cd90432760bcef0eaa13975d6178bd62f5cdaf8f59d7ecd3e3d1d63ce760723cbf089fead30ac23c0af51885e03c219ddbd4563dfb10716e",
          "sha256": "d36984d3e8bfdba1a2b9e9d782ddb2312e902cc5b939c12cf5b1c51c894050a4",
          "sha1": "1842ba4b68c9af2893bef38e18763cdaf54b4262",
          "md5": "83e2aa0466d4e62a8902fb8b59523e7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.8-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.8-20201016.074218-1.jar",
          "size": 11833,
          "sha512": "b06cfd98af52fec4cd90432760bcef0eaa13975d6178bd62f5cdaf8f59d7ecd3e3d1d63ce760723cbf089fead30ac23c0af51885e03c219ddbd4563dfb10716e",
          "sha256": "d36984d3e8bfdba1a2b9e9d782ddb2312e902cc5b939c12cf5b1c51c894050a4",
          "sha1": "1842ba4b68c9af2893bef38e18763cdaf54b4262",
          "md5": "83e2aa0466d4e62a8902fb8b59523e7a"
        }
      ]
    }
  ]
}
