{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-example",
    "version": "0.0.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "hiv6pk5ernfrxg6irztxbtvmou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.10-20210407.122610-1.jar",
          "size": 12003,
          "sha512": "799ba0b19f831e8dc9127770a7e6a817fa50d325c73473d54af72e2af38160fcc7e5d96b577e750d966dd990cf51c12c9d8e96f44377daa12e982c38e10791f7",
          "sha256": "4e3a9778cca0133674b68039b402ed2fa7d685bd86fde6bb6b028a43ea725694",
          "sha1": "59b9a16ac6307bf2690e56226d2c4d69e786d03b",
          "md5": "7190b178a4243909144c97244420f7e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-inventory-agent-for-java-core",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-example-0.0.10-SNAPSHOT.jar",
          "url": "soracom-inventory-agent-for-java-example-0.0.10-20210407.122610-1.jar",
          "size": 12003,
          "sha512": "799ba0b19f831e8dc9127770a7e6a817fa50d325c73473d54af72e2af38160fcc7e5d96b577e750d966dd990cf51c12c9d8e96f44377daa12e982c38e10791f7",
          "sha256": "4e3a9778cca0133674b68039b402ed2fa7d685bd86fde6bb6b028a43ea725694",
          "sha1": "59b9a16ac6307bf2690e56226d2c4d69e786d03b",
          "md5": "7190b178a4243909144c97244420f7e0"
        }
      ]
    }
  ]
}
