{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zgzcdyvucvaafoasp3garrvfaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "14eca9023600529a40fc4cbe4cc2f27f50f19170e0e2869cfb33c1a6b05385c285e4749eb7b62885adb943c151a154c0c3f2a106cd8ba12d30ccbe9ec31d4ba5",
          "sha256": "c2575756f7a33c99c3417a12167cabfecb13043197b19aac1420d3219a498114",
          "sha1": "50ee5490161ab14f3b0e97b89814b2172063e326",
          "md5": "96c56890368aa56dbb0625d6062b5d81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "14eca9023600529a40fc4cbe4cc2f27f50f19170e0e2869cfb33c1a6b05385c285e4749eb7b62885adb943c151a154c0c3f2a106cd8ba12d30ccbe9ec31d4ba5",
          "sha256": "c2575756f7a33c99c3417a12167cabfecb13043197b19aac1420d3219a498114",
          "sha1": "50ee5490161ab14f3b0e97b89814b2172063e326",
          "md5": "96c56890368aa56dbb0625d6062b5d81"
        }
      ]
    }
  ]
}
