{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ji2gbsqpizgxhpzvouublrc5sm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "c9a26a0401de25dba2a2fc59bd9b848410c0aad7af880878584aa1f34f8d51389d749e20cca79575913301afe27fd33c3eb10c180600aafde29a2654601a28ab",
          "sha256": "510895e0b60b6fd58df36fb93b3fbd1689b103e328303f229c734ee0c1e21539",
          "sha1": "d6492ed7e45dbaecd754c442c44aa28fb3c7e023",
          "md5": "d255e972aa493f7c9c04b5d845a5331d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "c9a26a0401de25dba2a2fc59bd9b848410c0aad7af880878584aa1f34f8d51389d749e20cca79575913301afe27fd33c3eb10c180600aafde29a2654601a28ab",
          "sha256": "510895e0b60b6fd58df36fb93b3fbd1689b103e328303f229c734ee0c1e21539",
          "sha1": "d6492ed7e45dbaecd754c442c44aa28fb3c7e023",
          "md5": "d255e972aa493f7c9c04b5d845a5331d"
        }
      ]
    }
  ]
}
