{
  "formatVersion": "1.1",
  "component": {
    "group": "io.soracom",
    "module": "soracom-inventory-agent-for-java-core",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ckgmfaa4zfeo5ewoqomjquktea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "dac91ab8dcfed4d3187fb80371f5ce83ae80b0d67000c4a4e4f1a226b0d90ac5c636b082062eea5fad9ba260ca2b09654980acec490037621b7e4346e40cb4df",
          "sha256": "94af94ea6cd9f06ef63a1da3dde4e6739bceabbbb7d1e0de1d8e4a63e4ca8b6a",
          "sha1": "8401fd566e7c7b76c9b27d597fce70c65f1815b",
          "md5": "c1622ff27fe63679fec7254b96caf6c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.eclipse.leshan",
          "module": "leshan-client-cf",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.soracom",
          "module": "soracom-krypton-client-for-java",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "url": "soracom-inventory-agent-for-java-core-0.0.9.jar",
          "size": 127581,
          "sha512": "dac91ab8dcfed4d3187fb80371f5ce83ae80b0d67000c4a4e4f1a226b0d90ac5c636b082062eea5fad9ba260ca2b09654980acec490037621b7e4346e40cb4df",
          "sha256": "94af94ea6cd9f06ef63a1da3dde4e6739bceabbbb7d1e0de1d8e4a63e4ca8b6a",
          "sha1": "8401fd566e7c7b76c9b27d597fce70c65f1815b",
          "md5": "c1622ff27fe63679fec7254b96caf6c7"
        }
      ]
    }
  ]
}
